
ADDED_AT = 'added_at'
MODIFIED_AT = 'modified_at'
POST = 'POST'
RESPONSE = 'response'
SUCCESS = 'success'
FAILURE = 'failure'
NAME = 'name'
STOCK = 'stock'
BOOK_STORE_TABLE = 'bookStore'
SELECTED = 'selected'

BASE_PATH = 'inventory/base.html'
CREATE_PATH = 'inventory/modals/create.html'
DELETE_PATH = 'inventory/modals/delete.html'
VIEW_PATH = 'inventory/modals/view.html'
BASE_MODAL_PATH = 'inventory/modals/base_modal.html'
INPUT_PATH = 'input_path'
ENTRIES = 'entries'
BOOK_ID = 'book_id'
MAIN_VIEW = 'inventory:index'
DUPLICATE = 'Already Exists '
ERROR = 'error'  