# Generated by Django 3.2.4 on 2021-06-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='added_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='book_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
