# Generated by Django 3.2.4 on 2021-06-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210620_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='descriptions',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='photo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='publisher',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
