# Generated by Django 3.2.4 on 2021-06-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210620_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstore',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookstore',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='bookstore',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='bookstore',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bookstore',
            name='publisher',
        ),
    ]
